### ISSUE TITLE
formatterのページ相談

### ISSUE THREAD

**Issue by h-sao** [cppmap/cppmap.docs#35]
新規ページの相談です
formatterの紹介ページがあってもいいかなと思いました
（わたし自身はclang-format くらいしか使ったことないのですが…）
入れるならツールの下になるかな？どうでしょう！？

**Comment by Reputeless** [comment]
ご提案ありがとうございます。あると便利だと思いました！
空ページを用意したので、もし良かったら加筆していただけると嬉しいです。
網羅的である必要はありません。僕も時間があれば追記していきます。

**Comment by h-sao** [comment]
空ベージありがとうございます〜
了解です、書けそうなところを書いてPR出しますね

**Comment by h-sao** [comment]
軽く記載したのでPRのために別ブランチをpushしようとしたら権限が無いみたいです

**Comment by Reputeless** [comment]
更新ありがとうございます！
cppmap/cppmap.docs は直接編集できないようになっているので、
お手数ですが、cppmap/cppmap.docs を Fork し、
編集を加えたコミットを作成、それから pull-request を作成してみてください。

**Comment by h-sao** [comment]
Oops.....! 寝ぼけてましたすみません
#36 です。よろしくお願いします！
