### ISSUE TITLE
C++20コルーチンのライブラリをどこで紹介すればいいか

### ISSUE THREAD

**Issue by yumetodo** [cppmap/cppmap.docs#39]
C++20のコルーチンはライブラリ側を提供していません。

そこで
https://github.com/lewissbaker/cppcoro
という良さそうなものがあるのですが、どこの分類で紹介するべきでしょうか？「並行・並列」でしょうか

**Comment by Reputeless** [comment]
ご提案ありがとうございます。
`library/multi-threading.md` を `library/concurrency.md` にリネームしたので 5eb6c4c,
そこに新しい小見出し `## コルーチン` を作って情報を加えてください。
