### ISSUE TITLE
gitignoreのテンプレを追記したい相談

### ISSUE THREAD

**Issue by h-sao** [cppmap/cppmap.docs#47]
ふとC++作業してた時に思ったのですが
GitHubのgitignoreのテンプレがどこかに記載あると嬉しいかなと思いました
まぁ…リンクは検索すればすぐに探せるのですが
- [C++.gitignore](https://github.com/github/gitignore/blob/main/C%2B%2B.gitignore)
- [VisualStudio.gitignore](https://github.com/github/gitignore/blob/main/VisualStudio.gitignore)
このリンクを、[C++ プロジェクト・テンプレート]の中？とかに入れるのはどうでしょうか？
> 悩ましいのが、上記２つだけファイルに直接リンクするのもなぁと思いつつ、  
https://github.com/github/gitignore この大元のリポジトリだと、とび先からC++ファイルを探すのが面倒という気もしてます

ジャストアイデアであまり深く練ってませんが、いいアイデアがあれば。。。

**Comment by Reputeless** [comment]
ご提案ありがとうございます！ 確かに有用な情報です。
新しく `cppmap.docs/docs/tools/gitignore.md` を作り、最初を
```md
description: C++ 用 .gitignore の紹介

# C++ 用 .gitignore


```

として、内容を（ただのリストでも OK) 書いて Pull-req いただければ、
マージ・反映します (mkdocs.yml の更新は、こちらでやっておきます)。
読者はファイルの内容をすぐに見たいと思うので、リンクはファイルに直接が便利だと思います。

**Comment by h-sao** [comment]
了解ですー
またプルリク出しておきます👍
