### ISSUE TITLE
書籍の情報を追加したいです

### ISSUE THREAD

**Issue by liliilli** [cppmap/cppmap.docs#5]
お世話になります。外国から拝見しています。

突然ですが私が今まで読んだC++の書籍の中で役に立った書籍が何冊がありましたのでここに記しておきたいと思います。全部洋書ですがもしかして宜しければご追加しますようお願いいたします。

１．C++ Template Complete Guide second edition
https://www.amazon.com/C-Templates-Complete-Guide-2nd/dp/0321714121
https://www.oreilly.com/library/view/c-templates-the/9780134778808/#toc-start
C++17までのテンプレート文法や機能、テクニックに関して総網羅した本です。以前の処版はC++03までの知識までを扱ったそうですが、この新版はC++17はもちろん、C++20の機能のプレビューまで書いています。ある程度のテンプレート知識があれば誰でもほぼ読みやすい英語と展開で記述されていたと思います。

２．API design for C++
https://www.amazon.com/API-Design-C-Martin-Reddy-ebook/dp/B004NNUZ6O
扱っているC++の内容はちょっと古いですが（C++03を主にして、C++11は補助）、C++を使用したライブラリなどのAPIデザインに関して集中的に書いています。個人的にはEffectiveシリーズと一緒に読んでも良さそうと思いました。

３．Mastering the C++17 STL
https://www.packtpub.com/application-development/mastering-c17-stl
C++17から追加したSTLの機能たちを重点的に取り扱っています。 レファランス本として見てもいいと思います。

４．C++ Concurrency in Action, Second Edition
https://www.manning.com/books/c-plus-plus-concurrency-in-action-second-edition
C++17までの並列プログラミング文法、機能、そして最終的にはLock-freeな構造体のデザインの作り方まで書いています。英語の難易度はこの４本の中で一番高いと思いました。

**Comment by Reputeless** [comment]
情報ありがとうございます。追加します。

**Comment by liliilli** [comment]
ありがとうございます。ところで２番のAPI Design for C++ですが、和訳版があるようです。
「C++のためのAPIデザイン」
https://goo.gl/oBRZtJ

韓国ではこの和訳書のKindle版が買えないんですので、和訳版はどのようになっているかはわからないんですが、もしかして日本現地で購入できればご検討後、これも追加しますようお願いいたします。

**Comment by Reputeless** [comment]
和訳版を持っています。
英語版と同じで基本的に C++03 + boost のコードですが、ときどき C++11 (策定途中だったので C++0x) の機能が登場します。
ただ、`[[override]] 属性` など、先走って誤った情報も含まれています。

こうした C++11 策定の少し前の時代 (2009〜2011年) の本は「C++0x 時代の本」として分類する予定です。

**Comment by Reputeless** [comment]
追加しました。
https://cppmap.github.io/learn/books/#_2
