### ISSUE TITLE
オススメの C++17 洋書を 2 つほど

### ISSUE THREAD

**Issue by kariya-mitsuru** [cppmap/cppmap.docs#6]
- [C++17 in Detail](https://leanpub.com/cpp17indetail)
- [C++17 - The Complete Guide](http://www.cppstd17.com) ただし、まだドラフト

**Comment by Reputeless** [comment]
情報ありがとうございます。調査してリストに加えます。

**Comment by Reputeless** [comment]
とりあえず、完成している前者のほうを掲載します。

**Comment by Reputeless** [comment]
両方とも出版されたので更新しました: d74d99f
情報提供ありがとうございました。
